[package]
name = "gazetta-bin"
version = "0.1.0"
authors = ["Steven Allen <steven@stebalien.com>"]

[[bin]]
name="gazetta"
path="src/main.rs"

[profile.dev]
codegen-units=4

[dependencies.gazetta]
#git = "https://github.com/Stebalien/gazetta.git"
path = "../gazetta"

[dependencies]
horrorshow = "*"
